import {requestRideOrigin,rideCoordinates} from './ride-position.js';
export function createTownMap(world,onChoose,onToggle,navigation,onNavigate){
 const locationName=world.data.locationName||'Shelby Township',labels=new Set(world.data.mapLabels||['Mile Road','Shelby Road','Dequindre Road','Hayes Road','Van Dyke Avenue']);const panel=document.createElement('section');panel.id='townMap';panel.className='hidden';panel.innerHTML='<div class="town-map-head"><div><small class="map-location"></small><h2>Choose your destination.</h2></div><button aria-label="Close street map">×</button></div><p>Click a road to navigate there. <span>Amber: road hazards · Red: near misses · H reports a pothole</span></p><canvas></canvas>';panel.querySelector('.map-location').textContent=`${locationName}, Michigan`;const canvas=panel.querySelector('canvas');canvas.setAttribute('aria-label',`Map of ${locationName} streets`);document.querySelector('#app').append(panel);const ctx=canvas.getContext('2d');let open=false,current=null,transform=null,mode='navigate',layer='all';
 const actions=document.createElement('div');actions.className='map-actions';
 actions.innerHTML='<button data-mode="navigate" aria-pressed="true">Navigate here</button><button data-mode="relocate" aria-pressed="false">Move rider here</button><button data-clear>End route</button><button data-location>Use MacBook location</button><select aria-label="Safety map layer" data-layer><option value="all">All hazards</option><option value="pothole">Potholes</option><option value="debris">Debris</option><option value="roadworks">Construction</option><option value="near_miss">Near-miss heatmap</option><option value="dangerous_intersection">Intersection heatmap</option></select>';
 panel.insertBefore(actions,canvas);
 const locationStatus=document.createElement('p');locationStatus.setAttribute('role','status');panel.insertBefore(locationStatus,canvas);
 actions.querySelector('[data-location]').onclick=async()=>{locationStatus.textContent='Finding starting location…';try{world.rideOrigin=await requestRideOrigin({...current});locationStatus.textContent=`Starting location set · ±${Math.round(world.rideOrigin.accuracy)} m · movement from game`;draw();}catch(e){locationStatus.textContent=e.message;}};
 actions.querySelector('[data-layer]').onchange=e=>{layer=e.target.value;draw();};

 actions.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{mode=button.dataset.mode;actions.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));});
 actions.querySelector('[data-clear]').onclick=()=>{navigation.clear();draw();};
 const b=world.data.townshipBoundary;const xs=b.map(p=>p[0]),ys=b.map(p=>p[1]);const bounds=[Math.min(...xs)-200,Math.min(...ys)-200,Math.max(...xs)+200,Math.max(...ys)+200];
 const businesses=world.data.businesses||[];
 if(businesses.length){const legend=document.createElement('p');legend.textContent=businesses.map((shop,i)=>`${i+1}. ${shop.name}`).join(' · ');panel.insertBefore(legend,canvas)}
 function draw(){const rect=canvas.getBoundingClientRect();canvas.width=rect.width*devicePixelRatio;canvas.height=rect.height*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const width=rect.width,height=rect.height;ctx.fillStyle='#182222';ctx.fillRect(0,0,width,height);const scale=Math.min((width-35)/(bounds[2]-bounds[0]),(height-35)/(bounds[3]-bounds[1])),ox=(width-(bounds[2]-bounds[0])*scale)/2,oy=(height-(bounds[3]-bounds[1])*scale)/2;transform={scale,ox,oy};const pos=p=>[ox+(p[0]-bounds[0])*scale,oy+(bounds[3]-p[1])*scale];
 for(const road of world.data.roads){if(road.class==='service')continue;const major=['motorway','trunk','primary','secondary'].includes(road.class);ctx.strokeStyle=major?'#d1d7c8':'#6b837d';ctx.lineWidth=major?1.6:.65;ctx.beginPath();road.points.forEach((p,i)=>{const [x,y]=pos(p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
 if(navigation.points.length){ctx.strokeStyle='#79dfec';ctx.lineWidth=3;ctx.beginPath();navigation.points.forEach((p,i)=>{const [x,y]=pos(p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();}
 ctx.strokeStyle='#e5ad70';ctx.lineWidth=1.5;ctx.setLineDash([5,5]);ctx.beginPath();b.forEach((p,i)=>{const [x,y]=pos(p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.setLineDash([]);
 const labeled=new Set();ctx.font='11px Arial';ctx.fillStyle='#eceddf';for(const r of world.data.roads){if(labeled.has(r.name)||![...labels].some(label=>r.name.includes(label))||r.length<250)continue;const p=r.points[Math.floor(r.points.length/2)],[x,y]=pos(p);if(x<35||x>width-100||y<25||y>height-20)continue;ctx.fillText(r.name,x+4,y-5);labeled.add(r.name)}
 businesses.forEach((shop,i)=>{const [x,y]=pos(shop.point);ctx.fillStyle='#edbe82';ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#182222';ctx.textAlign='center';ctx.font='bold 10px Arial';ctx.fillText(String(i+1),x,y+3);ctx.textAlign='left'});
 for(const hazard of world.gameHazards||[]){
 if(hazard.expires&&hazard.expires*1000<Date.now())continue;
 if(layer!=='all'&&(hazard.kind||'pothole')!==layer)continue;
 if(['near_miss','dangerous_intersection'].includes(hazard.kind)){
 const [hx,hy]=pos([hazard.x,-hazard.z]);const radius=18+12*(hazard.confidence||.3),gradient=ctx.createRadialGradient(hx,hy,0,hx,hy,radius);gradient.addColorStop(0,'rgba(255,90,70,.55)');gradient.addColorStop(1,'rgba(255,90,70,0)');ctx.fillStyle=gradient;ctx.fillRect(hx-radius,hy-radius,radius*2,radius*2);
 }
const [x,y]=pos([hazard.x,-hazard.z]);ctx.fillStyle=hazard.kind==='near_miss'?'#ff6868':hazard.kind==='roadworks'?'#ffe078':hazard.source==='rider'?'#ffbd70':'#db8c46';ctx.beginPath();ctx.moveTo(x,y-5);ctx.lineTo(x+5,y+4);ctx.lineTo(x-5,y+4);ctx.closePath();ctx.fill();}
 if(current){const geo=rideCoordinates(current,world.rideOrigin);if(geo)locationStatus.textContent=`Ride position ${geo.latitude.toFixed(5)}, ${geo.longitude.toFixed(5)} · game-relative · origin ±${Math.round(geo.accuracy)} m`;const [x,y]=pos([current.x,-current.z]);ctx.strokeStyle='#f6b366';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,10,0,Math.PI*2);ctx.stroke()}}
 const toggle=p=>{open=!open;current=p||current;panel.classList.toggle('hidden',!open);onToggle(open);if(open)requestAnimationFrame(draw)};
 panel.querySelector('button').onclick=()=>toggle();canvas.onclick=e=>{const rect=canvas.getBoundingClientRect(),{scale,ox,oy}=transform,x=bounds[0]+(e.clientX-rect.left-ox)/scale,y=bounds[3]-(e.clientY-rect.top-oy)/scale,r=world.roadAt(x,-y);if(!r||r.distance>45)return;const px=r.s.a[0]+(r.s.b[0]-r.s.a[0])*r.t,py=r.s.a[1]+(r.s.b[1]-r.s.a[1])*r.t;if(mode==='navigate')onNavigate([px,py],r.road.name||'Destination');else onChoose({x:px,z:-py,y:r.height,heading:r.heading},r.road);toggle()};addEventListener('resize',()=>{if(open)draw()});return {toggle,isOpen:()=>open};
}
