import {laneCenter} from './road-layout.js';
import * as T from 'three';import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
export class World{
 constructor(data){this.data=data;this.grid=new Map();this.nodeDegree=new Map();this.segments=[];this.buildingGrid=new Map();this.circleGrid=new Map();for(const c of data.turningCircles||[]){for(let x=Math.floor((c.point[0]-c.radius)/50);x<=Math.floor((c.point[0]+c.radius)/50);x++)for(let y=Math.floor((c.point[1]-c.radius)/50);y<=Math.floor((c.point[1]+c.radius)/50);y++){const k=x+','+y;if(!this.circleGrid.has(k))this.circleGrid.set(k,[]);this.circleGrid.get(k).push(c)}}for(const road of data.roads){road.bounds=[Math.min(...road.points.map(p=>p[0])),Math.min(...road.points.map(p=>p[1])),Math.max(...road.points.map(p=>p[0])),Math.max(...road.points.map(p=>p[1]))];road.length=0;road.distances=[0];for(let i=1;i<road.points.length;i++){const a=road.points[i-1],b=road.points[i],len=Math.hypot(b[0]-a[0],b[1]-a[1]);if(len<.01)continue;const s={a,b,len,road,index:i};for(const node of [road.nodeIds[i-1],road.nodeIds[i]])this.nodeDegree.set(node,(this.nodeDegree.get(node)||0)+1);this.segments.push(s);road.length+=len;road.distances.push(road.length);for(let x=Math.floor((Math.min(a[0],b[0])-Math.max(road.width,40))/50);x<=Math.floor((Math.max(a[0],b[0])+Math.max(road.width,40))/50);x++)for(let y=Math.floor((Math.min(a[1],b[1])-Math.max(road.width,40))/50);y<=Math.floor((Math.max(a[1],b[1])+Math.max(road.width,40))/50);y++){const key=x+','+y;if(!this.grid.has(key))this.grid.set(key,[]);this.grid.get(key).push(s)}}}
 for(const b of data.buildings){const xs=b.points.map(p=>p[0]),ys=b.points.map(p=>p[1]);b.bounds=[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)];for(let x=Math.floor(b.bounds[0]/50);x<=Math.floor(b.bounds[2]/50);x++)for(let y=Math.floor(b.bounds[1]/50);y<=Math.floor(b.bounds[3]/50);y++){const k=x+','+y;if(!this.buildingGrid.has(k))this.buildingGrid.set(k,[]);this.buildingGrid.get(k).push(b)}}
 }
 elevation(x,z){if((Math.abs(x)>1700||Math.abs(z)>1700)&&this.data.outerTerrain){const d=this.data.outerTerrain,b=d.bounds,u=T.MathUtils.clamp((x-b[0])/(b[2]-b[0])*(d.nx-1),0,d.nx-1.001),v=T.MathUtils.clamp((-z-b[1])/(b[3]-b[1])*(d.ny-1),0,d.ny-1.001),i=Math.floor(u),j=Math.floor(v),a=u-i,c=v-j,h=d.heights,n=d.nx;return h[j*n+i]*(1-a)*(1-c)+h[j*n+i+1]*a*(1-c)+h[(j+1)*n+i]*(1-a)*c+h[(j+1)*n+i+1]*a*c}const d=this.data,n=d.resolution,u=T.MathUtils.clamp((x/d.size+.5)*(n-1),0,n-1.001),v=T.MathUtils.clamp((-z/d.size+.5)*(n-1),0,n-1.001),i=Math.floor(u),j=Math.floor(v),a=u-i,b=v-j,h=d.heights;return h[j*n+i]*(1-a)*(1-b)+h[j*n+i+1]*a*(1-b)+h[(j+1)*n+i]*(1-a)*b+h[(j+1)*n+i+1]*a*b}
 roadAt(x,z,previousHeight=null){const y=-z;let best=null,score=Infinity;for(const s of this.grid.get(Math.floor(x/50)+','+Math.floor(y/50))||[]){const {a,b,len,road}=s;const t=T.MathUtils.clamp(((x-a[0])*(b[0]-a[0])+(y-a[1])*(b[1]-a[1]))/(len*len),0,1),xx=a[0]+(b[0]-a[0])*t,yy=a[1]+(b[1]-a[1])*t,dist=Math.hypot(x-xx,y-yy),h=a[2]+(b[2]-a[2])*t;const value=dist+(previousHeight===null?0:Math.max(0,Math.abs(h-previousHeight)-2)*4);if(value<score){score=value;best={distance:dist,signedDistance:(x-xx)*(-(b[1]-a[1])/len)+(y-yy)*((b[0]-a[0])/len),height:h,surface:road.surface==='gravel'?'gravel':'asphalt',road,s,t,heading:Math.atan2(b[0]-a[0],b[1]-a[1])}}}return best}
 ground(x,z,previousHeight=null){for(const c of this.circleGrid.get(Math.floor(x/50)+','+Math.floor(-z/50))||[]){if(Math.hypot(x-c.point[0],-z-c.point[1])<c.radius)return {height:this.elevation(c.point[0],-c.point[1])+.06,surface:'asphalt',onRoad:true,road:null}}const r=this.roadAt(x,z,previousHeight);if(r&&Math.abs(r.signedDistance-(r.road.pavementOffset||0))<r.road.width/2+.8&&r.distance<r.road.width/2+1)return {...r,onRoad:true};return {height:this.elevation(x,z),surface:r&&r.distance<r.road.width/2+3?'gravel':'grass',onRoad:false,road:r?.road}}
 collision(x,z){const y=-z;for(const b of this.buildingGrid.get(Math.floor(x/50)+','+Math.floor(y/50))||[]){if(x<b.bounds[0]-.35||x>b.bounds[2]+.35||y<b.bounds[1]-.35||y>b.bounds[3]+.35)continue;let inside=false;const p=b.points;for(let i=0,j=p.length-1;i<p.length;j=i++){if(((p[i][1]>y)!=(p[j][1]>y))&&(x<(p[j][0]-p[i][0])*(y-p[i][1])/(p[j][1]-p[i][1])+p[i][0]))inside=!inside}if(inside)return true}return false}
 async build(scene,loader){
 const texture=async(n,srgb=true)=>{const t=await new T.TextureLoader().loadAsync('/assets/'+n);t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=8;if(srgb)t.colorSpace=T.SRGBColorSpace;return t};
 const [albedo,normal,rough]=await Promise.all([texture('asphalt-color.jpg'),texture('asphalt-normal.jpg',false),texture('asphalt-roughness.jpg',false)]);
 const asphalt=new T.MeshStandardMaterial({map:albedo,normalMap:normal,normalScale:new T.Vector2(.3,.3),roughnessMap:rough,roughness:.95,color:0xa2a4a3});const [cm,cn,cr]=await Promise.all([texture('concrete-color.jpg'),texture('concrete-normal.jpg',false),texture('concrete-roughness.jpg',false)]);const concrete=new T.MeshStandardMaterial({map:cm,normalMap:cn,roughnessMap:cr,normalScale:new T.Vector2(.07,.07),color:0xc1beb2,roughness:1});for(const t of [cm,cn,cr])t.repeat.set(3,3);const shoulder=asphalt.clone();shoulder.color.set(0x6a6459);
 const n=this.data.resolution,d=this.data,verts=[],uv=[],indices=[],colors=[];
 for(let j=0;j<n;j++)for(let i=0;i<n;i++){const x=(i/(n-1)-.5)*d.size,z=-(j/(n-1)-.5)*d.size;let h=d.heights[j*n+i];const road=this.roadAt(x,z);if(road&&!road.road.bridge){const a=T.MathUtils.clamp((road.distance-road.road.width/2)/5,0,1);h=h*a+(road.height-.09)*(1-a)}verts.push(x,h,z);uv.push(i/(n-1),j/(n-1));const c=new T.Color().setHSL(.19+Math.sin(x*.03)*.008,.19,.24+Math.sin(x*.013+z*.027)*.025);colors.push(c.r,c.g,c.b);if(i<n-1&&j<n-1){const a=j*n+i;indices.push(a,a+1,a+n,a+1,a+n+1,a+n)}}
 let g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();
 const aerial=await texture('aerial.jpg');aerial.wrapS=aerial.wrapT=T.ClampToEdgeWrapping;const terrain=new T.Mesh(g,new T.MeshStandardMaterial({map:aerial,roughness:1,color:0x92998b,side:T.DoubleSide}));terrain.receiveShadow=true;scene.add(terrain);
 const bounds=this.data.bounds;if(bounds){const v=[],ix=[],uv=[];const nx=Math.ceil((bounds[2]-bounds[0])/18),ny=Math.ceil((bounds[3]-bounds[1])/18);for(let j=0;j<=ny;j++)for(let i=0;i<=nx;i++){const x=bounds[0]+(bounds[2]-bounds[0])*i/nx,y=bounds[1]+(bounds[3]-bounds[1])*j/ny;let height=this.elevation(x,-y)-.18;const road=this.roadAt(x,-y);if(road&&!road.road.bridge){const blend=T.MathUtils.clamp((road.distance-road.road.width/2-12)/18,0,1);height=height*blend+(road.height-.24)*(1-blend)}v.push(x,height,-y);uv.push(x/8,y/8);if(i<nx&&j<ny){const k=j*(nx+1)+i;ix.push(k,k+1,k+nx+1,k+1,k+nx+2,k+nx+1)}}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(v,3));geo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));geo.setIndex(ix);geo.computeVertexNormals();const grass=await texture('grass-color.jpg');addTerrainTiles(scene,geo,new T.MeshStandardMaterial({map:grass,color:0x9a9d76,roughness:1}));}
 const groups=[[],[],[],[]];const stripe=[[],[]];const curbs=[],walks=[];
 const quad=roadStrip;for(const road of this.data.roads){groups[2].push(roadRibbon(road.points,road.width+1.2,road.pavementOffset||0,-.045));groups[road.surface==='concrete'?1:0].push(roadRibbon(road.points,road.width,road.pavementOffset||0));}
 for(const s of this.segments){const {a,b,len,road}=s;
 if(road.curb&&road.class!=='service'){const start=this.nodeDegree.get(road.nodeIds[s.index-1])>2?Math.min(8,len*.4):0,end=this.nodeDegree.get(road.nodeIds[s.index])>2?Math.min(8,len*.4):0,pa=a.map((v,k)=>v+(b[k]-v)*start/len),pb=b.map((v,k)=>v-(b[k]-a[k])*end/len);for(const side of [-1,1]){curbs.push(curbRibbon([pa,pb],side*(road.width/2-.10)));if(['residential','tertiary','unclassified'].includes(road.class))walks.push(roadRibbon([pa,pb],1.52,side*(road.width/2+2.25),.12))}}
 if(['service','residential','living_street'].includes(road.class))continue;
 const laneWidth=road.laneWidth||3.35,usable=road.lanes*laneWidth;
 for(const edge of [-1,1]){const q=quad(a,b,.12,edge*usable/2,.018);if(q)stripe[road.oneway&&edge<0?1:0].push(q)}
 if(!road.oneway){for(const offset of road.lanes%2?[-laneWidth/2,laneWidth/2]:[-.10,.10]){const q=quad(a,b,.10,offset,.021);if(q)stripe[1].push(q)}}
 for(let lane=1;lane<road.lanes;lane++){const offset=-usable/2+lane*laneWidth;if(!road.oneway&&(Math.abs(offset)<.3||road.lanes%2&&Math.abs(Math.abs(offset)-laneWidth/2)<.1))continue;for(let at=0;at<len;at+=12){const end=Math.min(at+3,len),pa=a.map((v,k)=>v+(b[k]-v)*at/len),pb=a.map((v,k)=>v+(b[k]-v)*end/len);const q=quad(pa,pb,.12,offset,.02);if(q)stripe[0].push(q)}}

 }
 addTiles(scene,curbs,concrete);addTiles(scene,walks,concrete);
 const circleMeshes=[];for(const c of this.data.turningCircles||[]){const [x,y]=c.point,h=this.elevation(x,-y)+.06,vertices=[x,h,-y],indices=[],uv=[.5,.5];for(let i=0;i<=64;i++){const a=i/64*Math.PI*2;vertices.push(x+Math.cos(a)*c.radius,h,-y-Math.sin(a)*c.radius);uv.push(Math.cos(a)*c.radius/5,Math.sin(a)*c.radius/5);if(i)indices.push(0,i,i+1)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();circleMeshes.push(g)}if(circleMeshes.length){const mesh=new T.Mesh(mergeGeometries(circleMeshes),concrete);mesh.receiveShadow=true;scene.add(mesh);circleMeshes.forEach(g=>g.dispose())}
 const mats=[asphalt,concrete,shoulder];groups.forEach((list,i)=>{if(!list.length)return;addTiles(scene,list,mats[i])});stripe.forEach((list,i)=>{if(!list.length)return;addTiles(scene,list,new T.MeshStandardMaterial({color:i?0xcbb361:0xdcdad0,roughness:.88,side:T.DoubleSide}))});
 const [brickMap,brickNormal,brickRough]=await Promise.all([texture('masonry-color.jpg'),texture('masonry-normal.jpg',false),texture('masonry-roughness.jpg',false)]);
 for(const t of [brickMap,brickNormal,brickRough])t.repeat.set(1.6,1.6);
 this.buildingManifest=await (await fetch('/assets/building-tiles.json')).json();this.loadedBuildingTiles=new Map();let loading=false,lastCheck=0;
 this.updateBuildings=async(p,force=false)=>{if(loading||!force&&performance.now()-lastCheck<1000)return;lastCheck=performance.now();loading=true;try{const wanted=this.buildingManifest.filter(t=>Math.hypot(t.x-p.x,-t.y-p.z)<2100).sort((a,b)=>Math.hypot(a.x-p.x,-a.y-p.z)-Math.hypot(b.x-p.x,-b.y-p.z));for(const tile of wanted){if(this.loadedBuildingTiles.has(tile.file))continue;const buildings=(await loader.loadAsync('/assets/building-tiles/'+tile.file)).scene;
buildings.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const m of (Array.isArray(o.material)?o.material:[o.material])){if(m.name==='Masonry brick'){m.map=brickMap;m.normalMap=brickNormal;m.roughnessMap=brickRough;m.normalScale=new T.Vector2(.65,.65);m.color.set(0xb5a99a);m.roughness=1;m.needsUpdate=true}if(m.map)m.map.anisotropy=8}}});scene.add(buildings);this.loadedBuildingTiles.set(tile.file,buildings)}for(const tile of this.buildingManifest){const object=this.loadedBuildingTiles.get(tile.file);if(object){const distance=Math.hypot(tile.x-p.x,-tile.y-p.z);object.visible=distance<2600;if(distance>4000){scene.remove(object);object.traverse(o=>{if(o.isMesh){o.geometry.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material]))m.dispose()}});this.loadedBuildingTiles.delete(tile.file)}}}}catch(error){console.warn('Building tile load failed; retrying',error)}finally{loading=false}};
 await this.updateBuildings(this.spawn(),true);
 }
 spawn(kind=0){if(kind===8||kind===9){
  const name=kind===8?'Van Dyke Avenue':'25 Mile Road',target=kind===8?[-652.58,7647.45]:[-687.58,7682.45];
  let best=null;
  for(const segment of this.segments){if(segment.road.name!==name)continue;let {a,b,len,road}=segment;
   if(!road.oneway&&(kind===8?b[1]<a[1]:b[0]<a[0]))[a,b]=[b,a];
   const t=T.MathUtils.clamp(((target[0]-a[0])*(b[0]-a[0])+(target[1]-a[1])*(b[1]-a[1]))/(len*len),0,1),x=a[0]+(b[0]-a[0])*t,y=a[1]+(b[1]-a[1])*t,distance=Math.hypot(x-target[0],y-target[1]);
   if(!best||distance<best.distance){const heading=Math.atan2(b[0]-a[0],b[1]-a[1]),offset=laneCenter(road);best={distance,x:x+Math.cos(heading)*offset,z:-y+Math.sin(heading)*offset,y:a[2]+(b[2]-a[2])*t,heading}}
  }
  if(best)return best;
 }
 const roads=this.data.roads.filter(r=>kind===4?r.name==='Althea Street':kind===5?/Dequindre/i.test(r.name):kind===6?/Hayes Road/i.test(r.name):kind===7?/Shelby Road/i.test(r.name):kind===2?/15 Mile/i.test(r.name):kind===3?/25 Mile/i.test(r.name):kind===1?r.class==='motorway'&&r.name.includes('Columbus')&&r.points.at(-1)[1]>r.points[0][1]:r.name==='Hall Road');const selected=roads.filter(r=>r.length>90).sort((a,b)=>{const c=r=>kind>=4?Math.abs(r.points[0][1]-4800):kind===1?Math.abs(r.points[0][0]-950)+Math.abs(r.points[0][1]-650):Math.abs(r.points[0][0])+Math.abs(r.points[0][1]+440);return c(a)-c(b)})[0]||roads[0];const a=selected.points[0],b=selected.points[1],heading=Math.atan2(b[0]-a[0],b[1]-a[1]);const laneOffset=laneCenter(selected);return {x:a[0]+Math.sin(heading)*12+Math.cos(heading)*laneOffset,z:-a[1]-Math.cos(heading)*12+Math.sin(heading)*laneOffset,y:a[2],heading}}
}

export function roadStrip(a,b,width,offset=0,raise=0){const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy);if(len<.01)return null;const nx=-dy/len,ny=dx/len;const v=[];for(const [p,s] of [[a,-1],[b,-1],[a,1],[b,1]])v.push(p[0]+nx*(offset+s*width/2),p[2]+raise,-p[1]-ny*(offset+s*width/2));const q=new T.BufferGeometry();q.setAttribute('position',new T.Float32BufferAttribute(v,3));q.setAttribute('uv',new T.Float32BufferAttribute([0,0,len/5,0,0,width/5,len/5,width/5],2));q.setIndex([0,1,2,1,3,2]);q.computeVertexNormals();return q}

// Shared vertices eliminate cracks at bends; capped miters avoid spikes.
export function roadRibbon(points,width,offset=0,raise=0){const vertices=[],uv=[],indices=[];let distance=0;for(let i=0;i<points.length;i++){const p=points[i],a=points[Math.max(0,i-1)],b=points[Math.min(points.length-1,i+1)];if(i)distance+=Math.hypot(p[0]-a[0],p[1]-a[1]);let dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy)||1;dx/=len;dy/=len;const next=points[Math.min(points.length-1,i+1)],prev=points[Math.max(0,i-1)];const ex=i<points.length-1?next[0]-p[0]:p[0]-prev[0],ey=i<points.length-1?next[1]-p[1]:p[1]-prev[1],el=Math.hypot(ex,ey)||1,miter=Math.min(1.7,1/Math.max(.59,Math.abs(dx*ex/el+dy*ey/el)));for(const side of [-1,1]){const o=(offset+side*width/2)*miter;vertices.push(p[0]-dy*o,p[2]+raise,-p[1]-dx*o);uv.push(distance/5,(side+1)*width/10)}if(i){const k=(i-1)*2;indices.push(k,k+2,k+1,k+2,k+3,k+1)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();return g}
export function curbRibbon(points,offset){const top=roadRibbon(points,.22,offset,.14),p=top.getAttribute('position'),v=Array.from(p.array),indices=Array.from(top.index.array),count=p.count;for(let i=0;i<count;i++)v.push(p.getX(i),p.getY(i)-.15,p.getZ(i));for(let i=0;i<count-2;i+=2){indices.push(i,i+count,i+2,i+2,i+count,i+count+2,i+1,i+3,i+count+1,i+3,i+count+3,i+count+1)}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(v,3));const uv=Array.from(top.getAttribute('uv').array);geo.setAttribute('uv',new T.Float32BufferAttribute([...uv,...uv],2));geo.setIndex(indices);geo.computeVertexNormals();top.dispose();return geo}

function addTiles(scene,list,material){const tiles=new Map();for(const g of list){g.computeBoundingBox();const c=g.boundingBox.getCenter(new T.Vector3()),key=Math.floor(c.x/300)+','+Math.floor(c.z/300);if(!tiles.has(key))tiles.set(key,[]);tiles.get(key).push(g)}for(const parts of tiles.values()){const g=mergeGeometries(parts);g.computeBoundingSphere();const mesh=new T.Mesh(g,material);mesh.receiveShadow=true;scene.add(mesh);parts.forEach(p=>p.dispose())}}

function addTerrainTiles(scene,source,material){const position=source.getAttribute('position'),normal=source.getAttribute('normal'),uv=source.getAttribute('uv'),index=source.index.array,tiles=new Map();for(let i=0;i<index.length;i+=3){const first=index[i],key=Math.floor(position.getX(first)/360)+','+Math.floor(position.getZ(first)/360);let tile=tiles.get(key);if(!tile){tile={lookup:new Map(),p:[],n:[],u:[],ix:[]};tiles.set(key,tile)}for(let j=0;j<3;j++){const id=index[i+j];if(!tile.lookup.has(id)){tile.lookup.set(id,tile.p.length/3);tile.p.push(position.getX(id),position.getY(id),position.getZ(id));tile.n.push(normal.getX(id),normal.getY(id),normal.getZ(id));tile.u.push(uv.getX(id),uv.getY(id))}tile.ix.push(tile.lookup.get(id))}}for(const t of tiles.values()){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(t.p,3));g.setAttribute('normal',new T.Float32BufferAttribute(t.n,3));g.setAttribute('uv',new T.Float32BufferAttribute(t.u,2));g.setIndex(t.ix);g.computeBoundingSphere();const m=new T.Mesh(g,material);m.receiveShadow=true;scene.add(m)}source.dispose()}
