import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';import {World,roadRibbon} from '../src/world.js';import {laneCenter,canTurn,turnPosition} from '../src/road-layout.js';import {RoadTraffic} from '../src/traffic.js';
const data=JSON.parse(fs.readFileSync(new URL('../public/assets/world.json',import.meta.url)));const world=new World(data);
test('township boundary and east/west residential network are present',()=>{assert.ok(data.townshipAreaSquareMiles>35);assert.ok(data.bounds[0]<-5500&&data.bounds[2]>4200);assert.ok(data.roads.filter(r=>r.class==='residential').length>3000);for(const name of ['Dequindre','Hayes','Shelby Road'])assert.ok(data.roads.some(r=>r.name.includes(name)));for(const kind of [4,5,6,7]){const p=world.spawn(kind);assert.ok(world.ground(p.x,p.z,p.y).onRoad)}});
test('typical subdivision cross section is 28 feet with correctly placed lanes',()=>{const roads=data.roads.filter(r=>r.widthSource==='MCDR 28 ft subdivision fallback');assert.ok(roads.length>1000);for(const r of roads){assert.ok(Math.abs(r.width-8.5344)<.001);assert.ok(laneCenter(r)>1.5&&laneCenter(r)<2)}});
test('turn restrictions prohibit forbidden exits and preserve only-turn routes',()=>{const rs=[{from:'a',via:'x',to:'b',kind:'no_left_turn'},{from:'c',via:'y',to:'d',kind:'only_right_turn'}];assert.equal(canTurn(rs,'a','b','x'),false);assert.equal(canTurn(rs,'a','z','x'),true);assert.equal(canTurn(rs,'c','e','y'),false);assert.equal(canTurn(rs,'c','d','y'),true)});
test('bent road ribbons retain shared cross sections and face upward',()=>{const g=roadRibbon([[0,0,0],[0,20,0],[15,35,0]],8.5344);assert.equal(g.getAttribute('position').count,6);for(const n of g.getAttribute('normal').array)assert.ok(Number.isFinite(n));assert.ok(g.getAttribute('normal').getY(2)>.99)});
test('turn paths are continuous across an intersection',()=>{const road={lanes:2,laneWidth:3.3528,oneway:false};const a={a:[0,0,0],b:[0,30,0],len:30,heading:0,road},b={a:[0,30,0],b:[30,30,0],len:30,heading:Math.PI/2,road};const x=turnPosition(a,b,.4999),y=turnPosition(a,b,.5001);assert.ok(Math.hypot(x.x-y.x,x.z-y.z)<.01);assert.ok(Math.abs(x.heading-y.heading)<.01)});
test('a neighborhood car makes a full stop before proceeding',()=>{const road={id:'a',class:'residential',lanes:2,laneWidth:3.3528,width:8.5344,oneway:true,points:[[0,0,0],[0,70,0],[0,140,0]],nodeIds:['a','b','c'],maxspeed:'25'};const traffic=new RoadTraffic({data:{roads:[road],signals:[],stops:[{node:'b',kind:'stop'}]}}),obj=new T.Object3D();obj.position.set(1.7,0,-20);const car={id:1,obj,edge:traffic.edges[0],distance:20,speed:9,next:traffic.edges[1],brake:[],wait:0};traffic.cars=[car];const player={x:100,z:-50,y:0,speed:0,crashed:true};let stopped=false;for(let i=0;i<1500;i++){traffic.update(1/60,player);if(car.edge===traffic.edges[0]&&car.distance>64&&car.speed<.2)stopped=true}assert.ok(stopped);assert.ok(car.edge===traffic.edges[1]||car.distance>66)});

test('Althea neighborhood has nearby regional building coverage',()=>{
 const p=world.spawn(4);const nearby=world.data.buildings.filter(b=>b.points.some(q=>Math.hypot(q[0]-p.x,-q[1]-p.z)<75));
 assert.ok(nearby.length>=2,'Neighborhood starts should not be empty due to missing footprint tiles');
});
