import {test} from 'node:test';import assert from 'node:assert/strict';import {signalPhase,followingSpeed,RoadTraffic} from '../src/traffic.js';import {World} from '../src/world.js';import fs from 'node:fs';
const data=JSON.parse(fs.readFileSync(new URL('../public/assets/world.json',import.meta.url)));const world=new World(data);
test('conflicting directions never share green and get clearance intervals',()=>{let allRed=0;for(let t=0;t<66;t+=.1){const a=signalPhase(t,0),b=signalPhase(t,1);assert.ok(!(a==='green'&&b==='green'));if(a==='red'&&b==='red')allRed++}assert.ok(allRed>20)});
test('traffic brakes for short following gaps and stays within desired speed',()=>{assert.equal(followingSpeed(20,2,0),0);assert.ok(followingSpeed(20,15,0)<10);assert.equal(followingSpeed(20,100,20),20)});
test('expanded corridor has both endpoints and connected signal approaches',()=>{for(const kind of [2,3]){const s=world.spawn(kind);assert.ok(world.ground(s.x,s.z).onRoad);assert.ok(-s.z>data.bounds[1]&&-s.z<data.bounds[3])}const traffic=new RoadTraffic(world);assert.ok(traffic.edges.filter(e=>e.signal).length>40);for(const edge of traffic.edges.slice(0,500)){const next=traffic.next(edge);if(next){assert.equal(next.from,edge.to);assert.notEqual(next.to,edge.from)}}});
test('M53 lane markings and pavement widths distinguish travel lanes from shoulders',()=>{for(const r of data.roads.filter(r=>r.name==='Christopher Columbus Freeway'&&r.class==='motorway')){assert.ok(r.lanes>=2);assert.equal(r.laneWidth,3.65);assert.ok(Math.abs(r.width-r.lanes*r.laneWidth-4.2)<.01);assert.equal(r.pavementOffset,-.9)}});

test('a moving car stops before a red signal and resumes on green',async()=>{const T=await import('three');const road={id:'a',class:'primary',lanes:1,laneWidth:3.35,width:4,oneway:true,points:[[0,0,0],[0,100,0],[0,200,0]],nodeIds:['a','b','c'],maxspeed:'35'};const fake={data:{roads:[road],signals:[{node:'b',point:[0,100]}]}};const traffic=new RoadTraffic(fake),edge=traffic.edges[0],obj=new T.Object3D();obj.position.set(1.7,0,-40);const car={obj,edge,distance:40,speed:12,next:traffic.edges[1],brake:[]};traffic.cars=[car];traffic.time=3;const rider={x:100,z:-50,y:0,speed:0,crashed:false,crash(){}};for(let i=0;i<600;i++)traffic.update(1/60,rider);assert.ok(car.distance<=94.001);assert.ok(car.speed<.05);traffic.time=33;for(let i=0;i<180;i++)traffic.update(1/60,rider);assert.ok(car.speed>3)});
test('freeway spawn faces north and stays on its own elevation layer',()=>{const p=world.spawn(1),g=world.ground(p.x,p.z,p.y);assert.ok(Math.cos(p.heading)>.8);assert.equal(g.road.class,'motorway');assert.ok(Math.abs(g.height-p.y)<1);assert.ok(g.distance<g.road.lanes*g.road.laneWidth/2)});
